##
#  This docker-compose file attempts to mimic a demo production-like environment
##
version: "3.7"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: secret
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SECRET_KEY: "yiese3IeNie3saequee4ash3Nae6pied2huh2aedeinahj6shiec9eilenguPhoh"
      DATABASE_URL: postgres://postgres:secret@db/postgres
  migrate:
    build: .
    depends_on:
      - db
    environment:
      SECRET_KEY: "yiese3IeNie3saequee4ash3Nae6pied2huh2aedeinahj6shiec9eilenguPhoh"
      DATABASE_URL: postgres://postgres:secret@db/postgres
    command: "/code/manage.py migrate --noinput"