format:
	/bin/sh -c ./script/format

lint:
	/bin/sh -c ./script/lint

makemessages:
	/bin/sh -c ./script/makemessages

compilemessages:
	/bin/sh -c ./script/compilemessages

test:
	/bin/sh -c ./script/test

cov:
	/bin/sh -c ./script/coverage
