site_name: "{{cookiecutter.project_title}} Documentation"
nav:
  - index.md
theme:
  name: material
  # favicon: assets/favicon.ico
  # logo: assets/logo.png
  language: en
  features:
    - search.suggest
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
