#! /bin/sh

# script/compilemessages: Compiles .po translation files to binary .mo files
set -e

RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
WHITE='\033[1;37m'

echo -e "\n${BLUE}==> Running django-admin compilemessages${NC}"
cd {{cookiecutter.project_slug}} DJANGO_SETTINGS_MODULE={{cookiecutter.project_slug}}.settings.develop && django-admin compilemessages