#! /bin/sh

# script/makemessages: Generate new .po translation files
set -e

RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
WHITE='\033[1;37m'

echo -e "\n${BLUE}==> Running django-admin makemessages…${NC}"
cd {{cookiecutter.project_slug}} && django-admin makemessages --all